### ISSUE TITLE
Main Pipeline - Last pass Loss issue 

### ISSUE THREAD

**Issue by AceVenturos** [AceVenturos/CSC4006-MEng-Research-Project#1]
GAN is now training under new CNN, current issue is that at the last pass of the training, peculiar issues arise in the loss function calculations. For batch size two, this is an assertion error at line,,

Batch size 4 trains okay.
Batch size 8 - 128 have a similar error (with some of the tensor sizes varying just):

Last pass for batch sizes 16, 32 and 64 error:

C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\loss.py:88: UserWarning: Using a target size (torch.Size([8, 128])) that is different to the input size (torch.Size([7, 128])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    model_wrapper.train(epochs=args.epochs, device=args.device)
  File "C:\Users\jmcke\Documents\Me\University\MEng\CSC4006 - Research and Development Project\Code\Semantic_Pyramid_for_Image_Generation-master\model_wrapper.py", line 181, in train
    loss_generator_diversity = w_div * self.diversity_loss(images_fake, noise_vector)
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jmcke\Documents\Me\University\MEng\CSC4006 - Research and Development Project\Code\Semantic_Pyramid_for_Image_Generation-master\lossfunction.py", line 107, in forward
    loss = self.l1_loss(latent_inputs_1, latent_inputs_2) / (
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 88, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\functional.py", line 2507, in l1_loss
    ret = torch.abs(input - target)
RuntimeError: The size of tensor a (7) must match the size of tensor b (8) at non-singleton dimension 0. 

For batch size 128:

C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\loss.py:88: UserWarning: Using a target size (torch.Size([40, 128])) that is different to the input size (torch.Size([39, 128])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    model_wrapper.train(epochs=args.epochs, device=args.device)
  File "C:\Users\jmcke\Documents\Me\University\MEng\CSC4006 - Research and Development Project\Code\Semantic_Pyramid_for_Image_Generation-master\model_wrapper.py", line 181, in train
    loss_generator_diversity = w_div * self.diversity_loss(images_fake, noise_vector)
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jmcke\Documents\Me\University\MEng\CSC4006 - Research and Development Project\Code\Semantic_Pyramid_for_Image_Generation-master\lossfunction.py", line 107, in forward
    loss = self.l1_loss(latent_inputs_1, latent_inputs_2) / (
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 88, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "C:\Users\jmcke\anaconda3\lib\site-packages\torch\nn\functional.py", line 2507, in l1_loss
    ret = torch.abs(input - target)
RuntimeError: The size of tensor a (39) must match the size of tensor b (40) at non-singleton dimension 0

If memory serves, batch size 8 has a tensor a (3) and tensor b (4)

**Comment by Ellenisawake** [comment]
A minor error (?): model_wrapper.py: line 157, use requires_grad=True within torch.no_grad.

To debug the size mismatch  error:
- confirm training set size (can be divided by 4?);
- make sure each training batch contains the same batch size samples.
Ultimately:
- lossfunction.py line 103: make sure latent_inputs.shape[0] is an even number.

**Comment by AceVenturos** [comment]
I made a silly error with batch sizes 32, 64 + 128 as 50,000 is indivisible by them. Though this doesn't explain batch sizes 16 and 8. Will look further

**Comment by AceVenturos** [comment]
Update: 49999/50000 images are being loaded. I believe this is due to the way the dataset is loaded through data.py Places365 object. 

Another theory is that there is a singular duplicate in the 50,000 line train.txt file Places365 uses to load the dataset.

**Comment by AceVenturos** [comment]
Tentatively think I've sorted it, original code uses pandas read_csv function but did not include 'header=None'. By default pandas.read_csv() reads first line as a header. 

Edit: Just double checked incase I removed the header from my train.txt, the original train.txt file doesn't contain a header either.

**Comment by AceVenturos** [comment]
Training working on batch size 50, I think this will have fixed the batch size 2 issue as well. Should be able to gain some results now
